# Generated by Django 5.2.10 on 2026-01-10 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_account_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.CharField(choices=[('SAVINGS', 'Savings'), ('CHECKING', 'Checking'), ('CREDIT', 'Credit'), ('TRANSACTION', 'Transaction'), ('LOAN', 'Loan'), ('CARD', 'Card')], max_length=12),
        ),
    ]
