# Generated by Django 4.2.20 on 2025-04-30 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_account_customer'),
        ('cards', '0002_card_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='account',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='card', to='accounts.account'),
        ),
    ]
