# Generated by Django 5.2.10 on 2026-01-11 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_alter_transaction_transaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='method',
            field=models.CharField(choices=[('ATM', 'ATM'), ('ONLINE', 'Online'), ('BRANCH', 'Branch')], default='ONLINE', max_length=10),
        ),
    ]
